name: soda-product-checks
version: v1
type: workflow
tags:
  - workflow
  - soda-checks
description: Empowering sales360 dp.
workspace: public
workflow:
  dag:
    - name: soda-job-v1
      spec:
        stack: soda+python:1.0
        compute: runnable-default
        resources:
          requests:
            cpu: 1000m
            memory: 250Mi
          limits:
            cpu: 1000m
            memory: 250Mi
        logLevel: INFO # WARNING, ERROR, DEBUG
        stackSpec:
          inputs:
            - dataset: dataos://icebase:sales360mockdb/product_data_master
              options:
                engine: minerva
                clusterName: system
              profile:
                columns:
                  - product_name
                  - class
                  - corp_item_prod_cat_name
              checks:
                - schema:
                    name: Confirm that required columns are present
                    fail:
                      when required column missing: [item_no,product_name]
                      when wrong column type:
                        unit_price: string
                    attributes:
                      category: Schema

                - invalid_count(product_name) = 0 :
                    valid min length: 5
                    name: Product name has 5 or more characters
                    warn: when between 5 and 27
                    fail: when > 27  
                    attributes:
                      category: Validity

                - duplicate_percent(item_no) < 1%:
                    attributes:
                      category: Uniqueness

                - row_count between 1 and 170:
                    attributes:
                      category: Accuracy

                - avg_length(corp_item_prod_cat_name) > 9:
                    attributes:
                      category: Accuracy





